version: "3.8"
services:
  backend:
    image: "phillysamurai/spring-react-fullstack:26.5.2021.15.23.0"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev